name: Chech PHP sources
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ~/wordpress/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
  
    - name: Composer Install
      run: composer install --prefer-dist --no-progress
      
    - name: Php check 
      run: wordpress/vendor/bin/phpcs wordpress/kredeum-nfts -n --ignore=lib --extensions=php --standard=WordPress
