name: Deploy to WordPress.org
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: true

      - name: Plugin Build
        run: pnpm run wp-build

      - name: Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: wordpress/kredeum-nfts/
          ASSETS_DIR: wordpress/assets
          SLUG: kredeum-nfts
